### ISSUE TITLE
A lot of memory ram usage

### ISSUE THREAD

**Issue by magonzalez192** [sol-lang/sol#4]
Recursive operations like recursive functions or loops consume big memory usage. For example:

```
a = 1
while a < 1000000 do
    a = a + 1
end
```

It will fill all RAM... Probably caused by GC bug.

It's only happend when there instrucions inside block, for example:

```
while 1 do end
```

This infinite loop, won't grow ram, and always will be called.

**Comment by Grissess** [comment]
It's a well known issue that Sol leaks memory; thanks for providing some test cases! I don't know if I can get this fixed promptly, because the error is probably systemic, but I will definitely use it as an allocator stress test.

You're likely noticing this issue because Sol leaks at least one integer for every comparison. It may or may not leak literals as well, though I haven't confirmed this behavior. Again, these bugs are notoriously hard to find.

In the meantime, note that you can compile with DEBUG_GC defined (add -DDEBUG_GC to CFLAGS in build.sh) to get a trace of the allocations and deallocations across functions into a file "gclog.txt" in the wd (this is _very_ slow). The distributed file gcstat.py can be run in Python to interpret these results and give some useful metrics. Feel free to look through these numbers for further memory tests (I will do this myself promptly).

**Comment by Grissess** [comment]
Thanks for the report! That test case was essential in finding a _major_ memory leak in comparison expressions. Let me know if the issue persists--it doesn't appear to on my side.
